[package]
name = "rust-client"
version = "0.1.0"
authors = ["Yaroslav Isakov <yaroslav.isakov@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = "3.1"

[target.'cfg(windows)'.dependencies]
vigemclient-sys = { version = "0.1", path="./vigemclient-sys" }
